---
name: Deploy app-dev

on:
  push:
    branches:
      - "app-dev"

jobs:
  deploy:
    uses: ./.github/workflows/slot_swap_reusable.yml
    name: Deploy app-dev
    with:
      environment: app-dev
    secrets: inherit
