---
name: Deploy prod

on:
  push:
    branches:
      - "prod"

jobs:
  deploy:
    uses: ./.github/workflows/acr_deploy_reusable.yml
    name: Deploy prod
    with:
      environment: prod
    secrets: inherit
